name: build-lambda-hello-world
on:
  push:
    branches: [main]
    paths:
      - applications/hello-world/**
      - .github/workflows/build-lambda-hello-world.yml
defaults: # パイプエラーを拾えるようにデフォルトシェルを設定
  run:
    shell: bash
concurrency: # コミット追加時に古いワークフローの実行を自動キャンセル
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    strategy:
      matrix:
        env: [prod] # 用意する環境に応じて変更
    runs-on: ubuntu-latest
    environment: ${{ matrix.env }}
    timeout-minutes: 5
    permissions:
      contents: read
      id-token: write
    env:
      ROLE_ARN: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ github.event.repository.name }}-${{ matrix.env }}-github-actions
      SESSION_NAME: gh-oidc-${{ github.run_id }}-${{ github.run_attempt }}
      ECR_REPOSITORY_URI: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{ github.event.repository.name }}-${{ matrix.env }}-hello-world
    steps:
      - uses: actions/checkout@v6
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.24"
      - name: Run lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.2.2
          working-directory: applications/hello-world
      - name: Run tests
        run: |
          cd applications/hello-world
          go test -v ./...
      - uses: aws-actions/configure-aws-credentials@v5 # 一時クレデンシャルの取得
        with:
          role-to-assume: ${{ env.ROLE_ARN }}
          role-session-name: ${{ env.SESSION_NAME }}
          aws-region: ${{ vars.AWS_REGION }}
      - uses: ./.github/actions/build-lambda/
        id: build
        with:
          ecr-repository-uri: ${{ env.ECR_REPOSITORY_URI }}
          function-name: hello-world
      # デプロイまで行う場合は次のようにする
      # - uses: ./.github/actions/deploy-lambda/
      #   with:
      #     function-name: ${{ github.event.repository.name }}-${{ matrix.env }}-hello-world
      #     image-uri: ${{ steps.build.outputs.image-uri }}
